// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trafficproxy.proto

package trafficproxy

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TrafficType int32

const (
	TrafficType_FLOW     TrafficType = 0
	TrafficType_INCIDENT TrafficType = 1
)

var TrafficType_name = map[int32]string{
	0: "FLOW",
	1: "INCIDENT",
}

var TrafficType_value = map[string]int32{
	"FLOW":     0,
	"INCIDENT": 1,
}

func (x TrafficType) String() string {
	return proto.EnumName(TrafficType_name, int32(x))
}

func (TrafficType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9c857d02e32d0eb6, []int{0}
}

type TrafficLevel int32

const (
	TrafficLevel_NO_LEVELS  TrafficLevel = 0
	TrafficLevel_CLOSED     TrafficLevel = 1
	TrafficLevel_CONGESTED  TrafficLevel = 3
	TrafficLevel_SLOW_SPEED TrafficLevel = 5
	TrafficLevel_FREE_FLOW  TrafficLevel = 7
	TrafficLevel_UNKNOWN    TrafficLevel = 10
)

var TrafficLevel_name = map[int32]string{
	0:  "NO_LEVELS",
	1:  "CLOSED",
	3:  "CONGESTED",
	5:  "SLOW_SPEED",
	7:  "FREE_FLOW",
	10: "UNKNOWN",
}

var TrafficLevel_value = map[string]int32{
	"NO_LEVELS":  0,
	"CLOSED":     1,
	"CONGESTED":  3,
	"SLOW_SPEED": 5,
	"FREE_FLOW":  7,
	"UNKNOWN":    10,
}

func (x TrafficLevel) String() string {
	return proto.EnumName(TrafficLevel_name, int32(x))
}

func (TrafficLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9c857d02e32d0eb6, []int{1}
}

type Action int32

const (
	Action_UPDATE Action = 0
	Action_DELETE Action = 1
)

var Action_name = map[int32]string{
	0: "UPDATE",
	1: "DELETE",
}

var Action_value = map[string]int32{
	"UPDATE": 0,
	"DELETE": 1,
}

func (x Action) String() string {
	return proto.EnumName(Action_name, int32(x))
}

func (Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9c857d02e32d0eb6, []int{2}
}

type IncidentType int32

const (
	IncidentType_ACCIDENT               IncidentType = 0
	IncidentType_CONGESTION             IncidentType = 1
	IncidentType_CONSTRUCTION           IncidentType = 2
	IncidentType_DISABLED_VEHICLE       IncidentType = 3
	IncidentType_EVENT                  IncidentType = 4
	IncidentType_MISCELLANEOUS          IncidentType = 5
	IncidentType_PLANNED_EVENT          IncidentType = 6
	IncidentType_ROAD_HAZARD            IncidentType = 7
	IncidentType_SCHEDULED_CONSTRUCTION IncidentType = 8
	IncidentType_WEATHER                IncidentType = 9
	IncidentType_POLICE                 IncidentType = 10
	IncidentType_ROAD_CLOSURE           IncidentType = 11
	IncidentType_ROAD_CONTRACTION       IncidentType = 12
)

var IncidentType_name = map[int32]string{
	0:  "ACCIDENT",
	1:  "CONGESTION",
	2:  "CONSTRUCTION",
	3:  "DISABLED_VEHICLE",
	4:  "EVENT",
	5:  "MISCELLANEOUS",
	6:  "PLANNED_EVENT",
	7:  "ROAD_HAZARD",
	8:  "SCHEDULED_CONSTRUCTION",
	9:  "WEATHER",
	10: "POLICE",
	11: "ROAD_CLOSURE",
	12: "ROAD_CONTRACTION",
}

var IncidentType_value = map[string]int32{
	"ACCIDENT":               0,
	"CONGESTION":             1,
	"CONSTRUCTION":           2,
	"DISABLED_VEHICLE":       3,
	"EVENT":                  4,
	"MISCELLANEOUS":          5,
	"PLANNED_EVENT":          6,
	"ROAD_HAZARD":            7,
	"SCHEDULED_CONSTRUCTION": 8,
	"WEATHER":                9,
	"POLICE":                 10,
	"ROAD_CLOSURE":           11,
	"ROAD_CONTRACTION":       12,
}

func (x IncidentType) String() string {
	return proto.EnumName(IncidentType_name, int32(x))
}

func (IncidentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9c857d02e32d0eb6, []int{3}
}

type IncidentSeverity int32

const (
	IncidentSeverity_BLOCKER    IncidentSeverity = 0
	IncidentSeverity_CRITICAL   IncidentSeverity = 1
	IncidentSeverity_MAJOR      IncidentSeverity = 2
	IncidentSeverity_MINOR      IncidentSeverity = 3
	IncidentSeverity_LOW_IMPACT IncidentSeverity = 4
)

var IncidentSeverity_name = map[int32]string{
	0: "BLOCKER",
	1: "CRITICAL",
	2: "MAJOR",
	3: "MINOR",
	4: "LOW_IMPACT",
}

var IncidentSeverity_value = map[string]int32{
	"BLOCKER":    0,
	"CRITICAL":   1,
	"MAJOR":      2,
	"MINOR":      3,
	"LOW_IMPACT": 4,
}

func (x IncidentSeverity) String() string {
	return proto.EnumName(IncidentSeverity_name, int32(x))
}

func (IncidentSeverity) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9c857d02e32d0eb6, []int{4}
}

type TrafficRequest struct {
	TrafficSource *TrafficSource `protobuf:"bytes,1,opt,name=trafficSource,proto3" json:"trafficSource,omitempty"`
	TrafficType   []TrafficType  `protobuf:"varint,2,rep,packed,name=trafficType,proto3,enum=trafficproxy.TrafficType" json:"trafficType,omitempty"`
	// Types that are valid to be assigned to RequestOneof:
	//	*TrafficRequest_TrafficAllRequest
	//	*TrafficRequest_TrafficWayIDsRequest
	//	*TrafficRequest_TrafficStreamingDeltaRequest
	RequestOneof isTrafficRequest_RequestOneof `protobuf_oneof:"request_oneof"`
	// timestamp of expected traffic data, number of milliseconds since the Epoch.
	// 0 means request for current(live) traffic data, otherwise request for archived traffic data.
	// For archived traffic data, only allows trafficAllRequest and trafficWayIDsRequest.
	Timestamp            int64    `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrafficRequest) Reset()         { *m = TrafficRequest{} }
func (m *TrafficRequest) String() string { return proto.CompactTextString(m) }
func (*TrafficRequest) ProtoMessage()    {}
func (*TrafficRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c857d02e32d0eb6, []int{0}
}

func (m *TrafficRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficRequest.Unmarshal(m, b)
}
func (m *TrafficRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficRequest.Marshal(b, m, deterministic)
}
func (m *TrafficRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficRequest.Merge(m, src)
}
func (m *TrafficRequest) XXX_Size() int {
	return xxx_messageInfo_TrafficRequest.Size(m)
}
func (m *TrafficRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficRequest proto.InternalMessageInfo

func (m *TrafficRequest) GetTrafficSource() *TrafficSource {
	if m != nil {
		return m.TrafficSource
	}
	return nil
}

func (m *TrafficRequest) GetTrafficType() []TrafficType {
	if m != nil {
		return m.TrafficType
	}
	return nil
}

type isTrafficRequest_RequestOneof interface {
	isTrafficRequest_RequestOneof()
}

type TrafficRequest_TrafficAllRequest struct {
	TrafficAllRequest *TrafficAllRequest `protobuf:"bytes,3,opt,name=trafficAllRequest,proto3,oneof"`
}

type TrafficRequest_TrafficWayIDsRequest struct {
	TrafficWayIDsRequest *TrafficWayIDsRequest `protobuf:"bytes,4,opt,name=trafficWayIDsRequest,proto3,oneof"`
}

type TrafficRequest_TrafficStreamingDeltaRequest struct {
	TrafficStreamingDeltaRequest *TrafficStreamingDeltaRequest `protobuf:"bytes,5,opt,name=trafficStreamingDeltaRequest,proto3,oneof"`
}

func (*TrafficRequest_TrafficAllRequest) isTrafficRequest_RequestOneof() {}

func (*TrafficRequest_TrafficWayIDsRequest) isTrafficRequest_RequestOneof() {}

func (*TrafficRequest_TrafficStreamingDeltaRequest) isTrafficRequest_RequestOneof() {}

func (m *TrafficRequest) GetRequestOneof() isTrafficRequest_RequestOneof {
	if m != nil {
		return m.RequestOneof
	}
	return nil
}

func (m *TrafficRequest) GetTrafficAllRequest() *TrafficAllRequest {
	if x, ok := m.GetRequestOneof().(*TrafficRequest_TrafficAllRequest); ok {
		return x.TrafficAllRequest
	}
	return nil
}

func (m *TrafficRequest) GetTrafficWayIDsRequest() *TrafficWayIDsRequest {
	if x, ok := m.GetRequestOneof().(*TrafficRequest_TrafficWayIDsRequest); ok {
		return x.TrafficWayIDsRequest
	}
	return nil
}

func (m *TrafficRequest) GetTrafficStreamingDeltaRequest() *TrafficStreamingDeltaRequest {
	if x, ok := m.GetRequestOneof().(*TrafficRequest_TrafficStreamingDeltaRequest); ok {
		return x.TrafficStreamingDeltaRequest
	}
	return nil
}

func (m *TrafficRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TrafficRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TrafficRequest_TrafficAllRequest)(nil),
		(*TrafficRequest_TrafficWayIDsRequest)(nil),
		(*TrafficRequest_TrafficStreamingDeltaRequest)(nil),
	}
}

type TrafficAllRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrafficAllRequest) Reset()         { *m = TrafficAllRequest{} }
func (m *TrafficAllRequest) String() string { return proto.CompactTextString(m) }
func (*TrafficAllRequest) ProtoMessage()    {}
func (*TrafficAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c857d02e32d0eb6, []int{1}
}

func (m *TrafficAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficAllRequest.Unmarshal(m, b)
}
func (m *TrafficAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficAllRequest.Marshal(b, m, deterministic)
}
func (m *TrafficAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficAllRequest.Merge(m, src)
}
func (m *TrafficAllRequest) XXX_Size() int {
	return xxx_messageInfo_TrafficAllRequest.Size(m)
}
func (m *TrafficAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficAllRequest proto.InternalMessageInfo

type TrafficWayIDsRequest struct {
	WayIDs               []int64  `protobuf:"zigzag64,1,rep,packed,name=wayIDs,proto3" json:"wayIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrafficWayIDsRequest) Reset()         { *m = TrafficWayIDsRequest{} }
func (m *TrafficWayIDsRequest) String() string { return proto.CompactTextString(m) }
func (*TrafficWayIDsRequest) ProtoMessage()    {}
func (*TrafficWayIDsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c857d02e32d0eb6, []int{2}
}

func (m *TrafficWayIDsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficWayIDsRequest.Unmarshal(m, b)
}
func (m *TrafficWayIDsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficWayIDsRequest.Marshal(b, m, deterministic)
}
func (m *TrafficWayIDsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficWayIDsRequest.Merge(m, src)
}
func (m *TrafficWayIDsRequest) XXX_Size() int {
	return xxx_messageInfo_TrafficWayIDsRequest.Size(m)
}
func (m *TrafficWayIDsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficWayIDsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficWayIDsRequest proto.InternalMessageInfo

func (m *TrafficWayIDsRequest) GetWayIDs() []int64 {
	if m != nil {
		return m.WayIDs
	}
	return nil
}

type TrafficStreamingDeltaRequest struct {
	StreamingRule        *TrafficStreamingDeltaRequest_StreamingRule `protobuf:"bytes,1,opt,name=streamingRule,proto3" json:"streamingRule,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *TrafficStreamingDeltaRequest) Reset()         { *m = TrafficStreamingDeltaRequest{} }
func (m *TrafficStreamingDeltaRequest) String() string { return proto.CompactTextString(m) }
func (*TrafficStreamingDeltaRequest) ProtoMessage()    {}
func (*TrafficStreamingDeltaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c857d02e32d0eb6, []int{3}
}

func (m *TrafficStreamingDeltaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficStreamingDeltaRequest.Unmarshal(m, b)
}
func (m *TrafficStreamingDeltaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficStreamingDeltaRequest.Marshal(b, m, deterministic)
}
func (m *TrafficStreamingDeltaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficStreamingDeltaRequest.Merge(m, src)
}
func (m *TrafficStreamingDeltaRequest) XXX_Size() int {
	return xxx_messageInfo_TrafficStreamingDeltaRequest.Size(m)
}
func (m *TrafficStreamingDeltaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficStreamingDeltaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficStreamingDeltaRequest proto.InternalMessageInfo

func (m *TrafficStreamingDeltaRequest) GetStreamingRule() *TrafficStreamingDeltaRequest_StreamingRule {
	if m != nil {
		return m.StreamingRule
	}
	return nil
}

type TrafficStreamingDeltaRequest_StreamingRule struct {
	// send flows by streaming when flow_count >= maxSize or not_send_time_interval >= maxTime seconds
	MaxSize              int32    `protobuf:"varint,1,opt,name=maxSize,proto3" json:"maxSize,omitempty"`
	MaxTime              int32    `protobuf:"varint,2,opt,name=maxTime,proto3" json:"maxTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrafficStreamingDeltaRequest_StreamingRule) Reset() {
	*m = TrafficStreamingDeltaRequest_StreamingRule{}
}
func (m *TrafficStreamingDeltaRequest_StreamingRule) String() string {
	return proto.CompactTextString(m)
}
func (*TrafficStreamingDeltaRequest_StreamingRule) ProtoMessage() {}
func (*TrafficStreamingDeltaRequest_StreamingRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c857d02e32d0eb6, []int{3, 0}
}

func (m *TrafficStreamingDeltaRequest_StreamingRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficStreamingDeltaRequest_StreamingRule.Unmarshal(m, b)
}
func (m *TrafficStreamingDeltaRequest_StreamingRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficStreamingDeltaRequest_StreamingRule.Marshal(b, m, deterministic)
}
func (m *TrafficStreamingDeltaRequest_StreamingRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficStreamingDeltaRequest_StreamingRule.Merge(m, src)
}
func (m *TrafficStreamingDeltaRequest_StreamingRule) XXX_Size() int {
	return xxx_messageInfo_TrafficStreamingDeltaRequest_StreamingRule.Size(m)
}
func (m *TrafficStreamingDeltaRequest_StreamingRule) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficStreamingDeltaRequest_StreamingRule.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficStreamingDeltaRequest_StreamingRule proto.InternalMessageInfo

func (m *TrafficStreamingDeltaRequest_StreamingRule) GetMaxSize() int32 {
	if m != nil {
		return m.MaxSize
	}
	return 0
}

func (m *TrafficStreamingDeltaRequest_StreamingRule) GetMaxTime() int32 {
	if m != nil {
		return m.MaxTime
	}
	return 0
}

type TrafficResponse struct {
	FlowResponses        []*FlowResponse     `protobuf:"bytes,1,rep,name=flowResponses,proto3" json:"flowResponses,omitempty"`
	IncidentResponses    []*IncidentResponse `protobuf:"bytes,2,rep,name=incidentResponses,proto3" json:"incidentResponses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TrafficResponse) Reset()         { *m = TrafficResponse{} }
func (m *TrafficResponse) String() string { return proto.CompactTextString(m) }
func (*TrafficResponse) ProtoMessage()    {}
func (*TrafficResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c857d02e32d0eb6, []int{4}
}

func (m *TrafficResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficResponse.Unmarshal(m, b)
}
func (m *TrafficResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficResponse.Marshal(b, m, deterministic)
}
func (m *TrafficResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficResponse.Merge(m, src)
}
func (m *TrafficResponse) XXX_Size() int {
	return xxx_messageInfo_TrafficResponse.Size(m)
}
func (m *TrafficResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficResponse proto.InternalMessageInfo

func (m *TrafficResponse) GetFlowResponses() []*FlowResponse {
	if m != nil {
		return m.FlowResponses
	}
	return nil
}

func (m *TrafficResponse) GetIncidentResponses() []*IncidentResponse {
	if m != nil {
		return m.IncidentResponses
	}
	return nil
}

type TrafficSource struct {
	Region               string   `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	TrafficProvider      string   `protobuf:"bytes,2,opt,name=trafficProvider,proto3" json:"trafficProvider,omitempty"`
	MapProvider          string   `protobuf:"bytes,3,opt,name=mapProvider,proto3" json:"mapProvider,omitempty"`
	Subregion            []string `protobuf:"bytes,4,rep,name=subregion,proto3" json:"subregion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrafficSource) Reset()         { *m = TrafficSource{} }
func (m *TrafficSource) String() string { return proto.CompactTextString(m) }
func (*TrafficSource) ProtoMessage()    {}
func (*TrafficSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c857d02e32d0eb6, []int{5}
}

func (m *TrafficSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficSource.Unmarshal(m, b)
}
func (m *TrafficSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficSource.Marshal(b, m, deterministic)
}
func (m *TrafficSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficSource.Merge(m, src)
}
func (m *TrafficSource) XXX_Size() int {
	return xxx_messageInfo_TrafficSource.Size(m)
}
func (m *TrafficSource) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficSource.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficSource proto.InternalMessageInfo

func (m *TrafficSource) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *TrafficSource) GetTrafficProvider() string {
	if m != nil {
		return m.TrafficProvider
	}
	return ""
}

func (m *TrafficSource) GetMapProvider() string {
	if m != nil {
		return m.MapProvider
	}
	return ""
}

func (m *TrafficSource) GetSubregion() []string {
	if m != nil {
		return m.Subregion
	}
	return nil
}

type FlowResponse struct {
	Flow                 *Flow    `protobuf:"bytes,1,opt,name=flow,proto3" json:"flow,omitempty"`
	Action               Action   `protobuf:"varint,2,opt,name=action,proto3,enum=trafficproxy.Action" json:"action,omitempty"`
	TrasctionID          string   `protobuf:"bytes,3,opt,name=trasctionID,proto3" json:"trasctionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlowResponse) Reset()         { *m = FlowResponse{} }
func (m *FlowResponse) String() string { return proto.CompactTextString(m) }
func (*FlowResponse) ProtoMessage()    {}
func (*FlowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c857d02e32d0eb6, []int{6}
}

func (m *FlowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlowResponse.Unmarshal(m, b)
}
func (m *FlowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlowResponse.Marshal(b, m, deterministic)
}
func (m *FlowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlowResponse.Merge(m, src)
}
func (m *FlowResponse) XXX_Size() int {
	return xxx_messageInfo_FlowResponse.Size(m)
}
func (m *FlowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FlowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FlowResponse proto.InternalMessageInfo

func (m *FlowResponse) GetFlow() *Flow {
	if m != nil {
		return m.Flow
	}
	return nil
}

func (m *FlowResponse) GetAction() Action {
	if m != nil {
		return m.Action
	}
	return Action_UPDATE
}

func (m *FlowResponse) GetTrasctionID() string {
	if m != nil {
		return m.TrasctionID
	}
	return ""
}

type SegmentedFlow struct {
	Speed                float32      `protobuf:"fixed32,1,opt,name=speed,proto3" json:"speed,omitempty"`
	TrafficLevel         TrafficLevel `protobuf:"varint,2,opt,name=trafficLevel,proto3,enum=trafficproxy.TrafficLevel" json:"trafficLevel,omitempty"`
	Begin                int32        `protobuf:"varint,3,opt,name=begin,proto3" json:"begin,omitempty"`
	End                  int32        `protobuf:"varint,4,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SegmentedFlow) Reset()         { *m = SegmentedFlow{} }
func (m *SegmentedFlow) String() string { return proto.CompactTextString(m) }
func (*SegmentedFlow) ProtoMessage()    {}
func (*SegmentedFlow) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c857d02e32d0eb6, []int{7}
}

func (m *SegmentedFlow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegmentedFlow.Unmarshal(m, b)
}
func (m *SegmentedFlow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegmentedFlow.Marshal(b, m, deterministic)
}
func (m *SegmentedFlow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentedFlow.Merge(m, src)
}
func (m *SegmentedFlow) XXX_Size() int {
	return xxx_messageInfo_SegmentedFlow.Size(m)
}
func (m *SegmentedFlow) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentedFlow.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentedFlow proto.InternalMessageInfo

func (m *SegmentedFlow) GetSpeed() float32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *SegmentedFlow) GetTrafficLevel() TrafficLevel {
	if m != nil {
		return m.TrafficLevel
	}
	return TrafficLevel_NO_LEVELS
}

func (m *SegmentedFlow) GetBegin() int32 {
	if m != nil {
		return m.Begin
	}
	return 0
}

func (m *SegmentedFlow) GetEnd() int32 {
	if m != nil {
		return m.End
	}
	return 0
}

type Flow struct {
	WayID                int64            `protobuf:"zigzag64,1,opt,name=wayID,proto3" json:"wayID,omitempty"`
	Speed                float32          `protobuf:"fixed32,2,opt,name=speed,proto3" json:"speed,omitempty"`
	TrafficLevel         TrafficLevel     `protobuf:"varint,3,opt,name=trafficLevel,proto3,enum=trafficproxy.TrafficLevel" json:"trafficLevel,omitempty"`
	Timestamp            int64            `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SegmentedFlow        []*SegmentedFlow `protobuf:"bytes,5,rep,name=segmentedFlow,proto3" json:"segmentedFlow,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Flow) Reset()         { *m = Flow{} }
func (m *Flow) String() string { return proto.CompactTextString(m) }
func (*Flow) ProtoMessage()    {}
func (*Flow) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c857d02e32d0eb6, []int{8}
}

func (m *Flow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Flow.Unmarshal(m, b)
}
func (m *Flow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Flow.Marshal(b, m, deterministic)
}
func (m *Flow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Flow.Merge(m, src)
}
func (m *Flow) XXX_Size() int {
	return xxx_messageInfo_Flow.Size(m)
}
func (m *Flow) XXX_DiscardUnknown() {
	xxx_messageInfo_Flow.DiscardUnknown(m)
}

var xxx_messageInfo_Flow proto.InternalMessageInfo

func (m *Flow) GetWayID() int64 {
	if m != nil {
		return m.WayID
	}
	return 0
}

func (m *Flow) GetSpeed() float32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *Flow) GetTrafficLevel() TrafficLevel {
	if m != nil {
		return m.TrafficLevel
	}
	return TrafficLevel_NO_LEVELS
}

func (m *Flow) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Flow) GetSegmentedFlow() []*SegmentedFlow {
	if m != nil {
		return m.SegmentedFlow
	}
	return nil
}

type IncidentResponse struct {
	Incident             *Incident `protobuf:"bytes,1,opt,name=incident,proto3" json:"incident,omitempty"`
	Action               Action    `protobuf:"varint,2,opt,name=action,proto3,enum=trafficproxy.Action" json:"action,omitempty"`
	TrasctionID          string    `protobuf:"bytes,3,opt,name=trasctionID,proto3" json:"trasctionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *IncidentResponse) Reset()         { *m = IncidentResponse{} }
func (m *IncidentResponse) String() string { return proto.CompactTextString(m) }
func (*IncidentResponse) ProtoMessage()    {}
func (*IncidentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c857d02e32d0eb6, []int{9}
}

func (m *IncidentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncidentResponse.Unmarshal(m, b)
}
func (m *IncidentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncidentResponse.Marshal(b, m, deterministic)
}
func (m *IncidentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncidentResponse.Merge(m, src)
}
func (m *IncidentResponse) XXX_Size() int {
	return xxx_messageInfo_IncidentResponse.Size(m)
}
func (m *IncidentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IncidentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IncidentResponse proto.InternalMessageInfo

func (m *IncidentResponse) GetIncident() *Incident {
	if m != nil {
		return m.Incident
	}
	return nil
}

func (m *IncidentResponse) GetAction() Action {
	if m != nil {
		return m.Action
	}
	return Action_UPDATE
}

func (m *IncidentResponse) GetTrasctionID() string {
	if m != nil {
		return m.TrasctionID
	}
	return ""
}

type Incident struct {
	IncidentID            string           `protobuf:"bytes,1,opt,name=incidentID,proto3" json:"incidentID,omitempty"`
	AffectedWayIDs        []int64          `protobuf:"zigzag64,2,rep,packed,name=affectedWayIDs,proto3" json:"affectedWayIDs,omitempty"`
	IncidentType          IncidentType     `protobuf:"varint,3,opt,name=incidentType,proto3,enum=trafficproxy.IncidentType" json:"incidentType,omitempty"`
	IncidentSeverity      IncidentSeverity `protobuf:"varint,4,opt,name=incidentSeverity,proto3,enum=trafficproxy.IncidentSeverity" json:"incidentSeverity,omitempty"`
	IncidentLocation      *Location        `protobuf:"bytes,5,opt,name=incidentLocation,proto3" json:"incidentLocation,omitempty"`
	Description           string           `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	FirstCrossStreet      string           `protobuf:"bytes,7,opt,name=firstCrossStreet,proto3" json:"firstCrossStreet,omitempty"`
	SecondCrossStreet     string           `protobuf:"bytes,8,opt,name=secondCrossStreet,proto3" json:"secondCrossStreet,omitempty"`
	StreetName            string           `protobuf:"bytes,9,opt,name=streetName,proto3" json:"streetName,omitempty"`
	EventCode             int32            `protobuf:"varint,10,opt,name=eventCode,proto3" json:"eventCode,omitempty"`
	AlertCEventQuantifier int32            `protobuf:"varint,11,opt,name=alertCEventQuantifier,proto3" json:"alertCEventQuantifier,omitempty"`
	IsBlocking            bool             `protobuf:"varint,12,opt,name=isBlocking,proto3" json:"isBlocking,omitempty"`
	Timestamp             int64            `protobuf:"varint,13,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}         `json:"-"`
	XXX_unrecognized      []byte           `json:"-"`
	XXX_sizecache         int32            `json:"-"`
}

func (m *Incident) Reset()         { *m = Incident{} }
func (m *Incident) String() string { return proto.CompactTextString(m) }
func (*Incident) ProtoMessage()    {}
func (*Incident) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c857d02e32d0eb6, []int{10}
}

func (m *Incident) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Incident.Unmarshal(m, b)
}
func (m *Incident) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Incident.Marshal(b, m, deterministic)
}
func (m *Incident) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Incident.Merge(m, src)
}
func (m *Incident) XXX_Size() int {
	return xxx_messageInfo_Incident.Size(m)
}
func (m *Incident) XXX_DiscardUnknown() {
	xxx_messageInfo_Incident.DiscardUnknown(m)
}

var xxx_messageInfo_Incident proto.InternalMessageInfo

func (m *Incident) GetIncidentID() string {
	if m != nil {
		return m.IncidentID
	}
	return ""
}

func (m *Incident) GetAffectedWayIDs() []int64 {
	if m != nil {
		return m.AffectedWayIDs
	}
	return nil
}

func (m *Incident) GetIncidentType() IncidentType {
	if m != nil {
		return m.IncidentType
	}
	return IncidentType_ACCIDENT
}

func (m *Incident) GetIncidentSeverity() IncidentSeverity {
	if m != nil {
		return m.IncidentSeverity
	}
	return IncidentSeverity_BLOCKER
}

func (m *Incident) GetIncidentLocation() *Location {
	if m != nil {
		return m.IncidentLocation
	}
	return nil
}

func (m *Incident) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Incident) GetFirstCrossStreet() string {
	if m != nil {
		return m.FirstCrossStreet
	}
	return ""
}

func (m *Incident) GetSecondCrossStreet() string {
	if m != nil {
		return m.SecondCrossStreet
	}
	return ""
}

func (m *Incident) GetStreetName() string {
	if m != nil {
		return m.StreetName
	}
	return ""
}

func (m *Incident) GetEventCode() int32 {
	if m != nil {
		return m.EventCode
	}
	return 0
}

func (m *Incident) GetAlertCEventQuantifier() int32 {
	if m != nil {
		return m.AlertCEventQuantifier
	}
	return 0
}

func (m *Incident) GetIsBlocking() bool {
	if m != nil {
		return m.IsBlocking
	}
	return false
}

func (m *Incident) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Location struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                  float64  `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c857d02e32d0eb6, []int{11}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Location) GetLon() float64 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func init() {
	proto.RegisterEnum("trafficproxy.TrafficType", TrafficType_name, TrafficType_value)
	proto.RegisterEnum("trafficproxy.TrafficLevel", TrafficLevel_name, TrafficLevel_value)
	proto.RegisterEnum("trafficproxy.Action", Action_name, Action_value)
	proto.RegisterEnum("trafficproxy.IncidentType", IncidentType_name, IncidentType_value)
	proto.RegisterEnum("trafficproxy.IncidentSeverity", IncidentSeverity_name, IncidentSeverity_value)
	proto.RegisterType((*TrafficRequest)(nil), "trafficproxy.TrafficRequest")
	proto.RegisterType((*TrafficAllRequest)(nil), "trafficproxy.TrafficAllRequest")
	proto.RegisterType((*TrafficWayIDsRequest)(nil), "trafficproxy.TrafficWayIDsRequest")
	proto.RegisterType((*TrafficStreamingDeltaRequest)(nil), "trafficproxy.TrafficStreamingDeltaRequest")
	proto.RegisterType((*TrafficStreamingDeltaRequest_StreamingRule)(nil), "trafficproxy.TrafficStreamingDeltaRequest.StreamingRule")
	proto.RegisterType((*TrafficResponse)(nil), "trafficproxy.TrafficResponse")
	proto.RegisterType((*TrafficSource)(nil), "trafficproxy.TrafficSource")
	proto.RegisterType((*FlowResponse)(nil), "trafficproxy.FlowResponse")
	proto.RegisterType((*SegmentedFlow)(nil), "trafficproxy.SegmentedFlow")
	proto.RegisterType((*Flow)(nil), "trafficproxy.Flow")
	proto.RegisterType((*IncidentResponse)(nil), "trafficproxy.IncidentResponse")
	proto.RegisterType((*Incident)(nil), "trafficproxy.Incident")
	proto.RegisterType((*Location)(nil), "trafficproxy.Location")
}

func init() { proto.RegisterFile("trafficproxy.proto", fileDescriptor_9c857d02e32d0eb6) }

var fileDescriptor_9c857d02e32d0eb6 = []byte{
	// 1236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcd, 0x6e, 0xdb, 0xc6,
	0x16, 0x16, 0x4d, 0x49, 0x96, 0x8e, 0x7e, 0x3c, 0x9e, 0xeb, 0x1b, 0xe8, 0xfa, 0xfa, 0xe6, 0x0a,
	0x04, 0x1a, 0x08, 0x42, 0x60, 0x14, 0x6e, 0x17, 0x05, 0x0a, 0x14, 0xa5, 0xc9, 0x49, 0xc4, 0x84,
	0x21, 0x9d, 0x21, 0x1d, 0x17, 0x5d, 0x54, 0x60, 0xa4, 0x91, 0x41, 0x54, 0x22, 0x55, 0x92, 0x76,
	0xe2, 0x3e, 0x40, 0x77, 0x5d, 0x74, 0xd3, 0x7d, 0x9f, 0xa5, 0x2f, 0x50, 0xa0, 0xdb, 0xbe, 0x45,
	0x37, 0x5d, 0x16, 0x33, 0x24, 0x2d, 0x52, 0x62, 0x82, 0x16, 0xe8, 0x4e, 0xe7, 0x3b, 0xdf, 0x7c,
	0xe7, 0xcc, 0xf9, 0x19, 0x11, 0x70, 0x12, 0x79, 0x8b, 0x85, 0x3f, 0x5b, 0x47, 0xe1, 0xdb, 0xbb,
	0xd3, 0x75, 0x14, 0x26, 0x21, 0xee, 0x16, 0x31, 0xe5, 0x37, 0x19, 0xfa, 0x6e, 0x0a, 0x50, 0xf6,
	0xcd, 0x0d, 0x8b, 0x13, 0xac, 0x42, 0x2f, 0xa3, 0x38, 0xe1, 0x4d, 0x34, 0x63, 0x03, 0x69, 0x28,
	0x8d, 0x3a, 0x67, 0xff, 0x3d, 0x2d, 0x89, 0xb9, 0x45, 0x0a, 0x2d, 0x9f, 0xc0, 0x9f, 0x42, 0x27,
	0x03, 0xdc, 0xbb, 0x35, 0x1b, 0xec, 0x0d, 0xe5, 0x51, 0xff, 0xec, 0x3f, 0x95, 0x02, 0x9c, 0x40,
	0x8b, 0x6c, 0x6c, 0xc3, 0x61, 0x66, 0xaa, 0xcb, 0x65, 0x96, 0xd4, 0x40, 0x16, 0x39, 0xfc, 0xbf,
	0x52, 0x62, 0x43, 0x9b, 0xd4, 0xe8, 0xee, 0x59, 0xfc, 0x05, 0x1c, 0x65, 0xe0, 0x95, 0x77, 0x67,
	0xe8, 0x71, 0xae, 0x59, 0x17, 0x9a, 0x4a, 0xa5, 0x66, 0x89, 0x39, 0xa9, 0xd1, 0x4a, 0x05, 0xbc,
	0x86, 0x93, 0xfc, 0xe2, 0x49, 0xc4, 0xbc, 0x95, 0x1f, 0x5c, 0xeb, 0x6c, 0x99, 0x78, 0x79, 0x84,
	0x86, 0x88, 0x30, 0xae, 0xae, 0x5c, 0xd5, 0x89, 0x49, 0x8d, 0xbe, 0x57, 0x11, 0x9f, 0x40, 0x3b,
	0xf1, 0x57, 0x2c, 0x4e, 0xbc, 0xd5, 0x7a, 0xd0, 0x1c, 0x4a, 0x23, 0x99, 0x6e, 0x80, 0xf3, 0x03,
	0xe8, 0x45, 0x29, 0x71, 0x1a, 0x06, 0x2c, 0x5c, 0x28, 0xff, 0x82, 0xc3, 0x9d, 0x22, 0x29, 0xa7,
	0x70, 0x54, 0x75, 0x4b, 0xfc, 0x00, 0x9a, 0x6f, 0x04, 0x30, 0x90, 0x86, 0xf2, 0x08, 0xd3, 0xcc,
	0x52, 0x7e, 0x96, 0xe0, 0xe4, 0x7d, 0x49, 0xe3, 0xaf, 0xa0, 0x17, 0xe7, 0x0e, 0x7a, 0xb3, 0xcc,
	0x27, 0xe6, 0x93, 0xbf, 0x7e, 0xef, 0x53, 0xa7, 0x78, 0x9e, 0x96, 0xe5, 0x8e, 0x35, 0xe8, 0x95,
	0xfc, 0x78, 0x00, 0xfb, 0x2b, 0xef, 0xad, 0xe3, 0x7f, 0x9b, 0x86, 0x6a, 0xd0, 0xdc, 0xcc, 0x3c,
	0xae, 0xbf, 0xe2, 0x53, 0x97, 0x7b, 0xb8, 0xa9, 0xfc, 0x24, 0xc1, 0xc1, 0xfd, 0xa4, 0xc7, 0xeb,
	0x30, 0x88, 0x19, 0xfe, 0x1c, 0x7a, 0x8b, 0x65, 0xf8, 0x26, 0xb7, 0xd3, 0x8b, 0x77, 0xce, 0x8e,
	0xcb, 0x89, 0x3f, 0x29, 0x50, 0x68, 0xf9, 0x00, 0x36, 0xe1, 0xd0, 0x0f, 0x66, 0xfe, 0x9c, 0x05,
	0xc9, 0x46, 0x65, 0x4f, 0xa8, 0x3c, 0x2c, 0xab, 0x18, 0x5b, 0x34, 0xba, 0x7b, 0x50, 0xf9, 0x41,
	0x82, 0x5e, 0x69, 0xb1, 0x78, 0x4f, 0x22, 0x76, 0xed, 0x87, 0x81, 0xb8, 0x68, 0x9b, 0x66, 0x16,
	0x1e, 0xc1, 0x41, 0xa6, 0x7e, 0x11, 0x85, 0xb7, 0xfe, 0x9c, 0x45, 0xe2, 0xbe, 0x6d, 0xba, 0x0d,
	0xe3, 0x21, 0x74, 0x56, 0xde, 0xfa, 0x9e, 0x25, 0x0b, 0x56, 0x11, 0xe2, 0x33, 0x15, 0xdf, 0xbc,
	0xce, 0xc2, 0xd4, 0x87, 0xf2, 0xa8, 0x4d, 0x37, 0x80, 0xf2, 0x9d, 0x04, 0xdd, 0x62, 0x05, 0xf0,
	0x23, 0xa8, 0xf3, 0x1a, 0x64, 0x4d, 0xc6, 0x15, 0xb5, 0x12, 0x7e, 0xfc, 0x18, 0x9a, 0xde, 0x2c,
	0xe1, 0x9a, 0x3c, 0xb3, 0xfe, 0xd9, 0x51, 0x99, 0xa9, 0x0a, 0x1f, 0xcd, 0x38, 0x3c, 0xcd, 0x24,
	0xf2, 0x62, 0x61, 0x18, 0x7a, 0x9e, 0x66, 0x01, 0x52, 0xbe, 0x97, 0xa0, 0xe7, 0xb0, 0xeb, 0x15,
	0x0b, 0x12, 0x36, 0xe7, 0x71, 0xf0, 0x11, 0x34, 0xe2, 0x35, 0x63, 0x73, 0x91, 0xca, 0x1e, 0x4d,
	0x0d, 0xfc, 0x19, 0xe4, 0x4f, 0x9c, 0xc9, 0x6e, 0xd9, 0x32, 0x8b, 0x7e, 0x5c, 0x39, 0x8c, 0x82,
	0x41, 0x4b, 0x7c, 0xae, 0xfa, 0x9a, 0x5d, 0xfb, 0x81, 0xc8, 0xa1, 0x41, 0x53, 0x03, 0x23, 0x90,
	0x59, 0x30, 0x17, 0x6f, 0x46, 0x83, 0xf2, 0x9f, 0xca, 0xaf, 0x12, 0xd4, 0xf3, 0x34, 0xc4, 0xa6,
	0x88, 0x34, 0x30, 0x4d, 0x8d, 0x4d, 0x72, 0x7b, 0xef, 0x4b, 0x4e, 0xfe, 0x9b, 0xc9, 0x95, 0xf6,
	0xbf, 0xbe, 0xb5, 0xff, 0xfc, 0xe9, 0x8e, 0x8b, 0x15, 0x1a, 0x34, 0xc4, 0x24, 0x6e, 0x3d, 0xdd,
	0xa5, 0x22, 0xd2, 0xf2, 0x09, 0xe5, 0x47, 0x09, 0xd0, 0xf6, 0xa8, 0xe2, 0x33, 0x68, 0xe5, 0xc3,
	0x9a, 0xb5, 0xfd, 0xc1, 0x3b, 0x86, 0xfb, 0x9e, 0xf7, 0x8f, 0xb7, 0xff, 0x97, 0x3a, 0xb4, 0xf2,
	0x30, 0xf8, 0x21, 0x40, 0x1e, 0x28, 0xab, 0x7b, 0x9b, 0x16, 0x10, 0xfc, 0x08, 0xfa, 0xde, 0x62,
	0xc1, 0x66, 0x09, 0x9b, 0xa7, 0x6f, 0x9c, 0xd8, 0x49, 0x4c, 0xb7, 0x50, 0xde, 0x8e, 0xfc, 0x94,
	0xf8, 0xa7, 0xaa, 0x6c, 0x87, 0x51, 0x60, 0xd0, 0x12, 0x1f, 0x3f, 0x03, 0x94, 0xdb, 0x0e, 0xbb,
	0x65, 0x91, 0x9f, 0xdc, 0x89, 0xae, 0xf4, 0xdf, 0xb5, 0xfd, 0x39, 0x8b, 0xee, 0x9c, 0xc3, 0xe7,
	0x1b, 0x2d, 0x33, 0x9c, 0x79, 0xa2, 0x74, 0x8d, 0xaa, 0x62, 0xe7, 0x5e, 0xba, 0xc3, 0xe7, 0x65,
	0x9c, 0xb3, 0x78, 0x16, 0xf9, 0x6b, 0x71, 0xbc, 0x99, 0x96, 0xb1, 0x00, 0xe1, 0x31, 0xa0, 0x85,
	0x1f, 0xc5, 0x89, 0x16, 0x85, 0x71, 0xcc, 0x5f, 0x55, 0x96, 0x0c, 0xf6, 0x05, 0x6d, 0x07, 0xc7,
	0x8f, 0xe1, 0x30, 0x66, 0xb3, 0x30, 0x98, 0x17, 0xc9, 0x2d, 0x41, 0xde, 0x75, 0xf0, 0x9e, 0xc4,
	0xe2, 0x97, 0xe5, 0xad, 0xd8, 0xa0, 0x9d, 0xf6, 0x64, 0x83, 0xf0, 0xd1, 0x65, 0xb7, 0x2c, 0x48,
	0xb4, 0x70, 0xce, 0x06, 0x20, 0xf6, 0x68, 0x03, 0xe0, 0x8f, 0xe1, 0xdf, 0xde, 0x92, 0x45, 0x89,
	0x46, 0x38, 0xf4, 0xf2, 0xc6, 0x0b, 0x12, 0x7f, 0xe1, 0xb3, 0x68, 0xd0, 0x11, 0xcc, 0x6a, 0xa7,
	0x98, 0x83, 0xf8, 0x7c, 0x19, 0xce, 0xbe, 0xf6, 0x83, 0xeb, 0x41, 0x77, 0x28, 0x8d, 0x5a, 0xb4,
	0x80, 0x94, 0xd7, 0xa5, 0xb7, 0xb5, 0x2e, 0xca, 0x29, 0xb4, 0xee, 0x2b, 0x87, 0x40, 0x5e, 0x7a,
	0xe9, 0x74, 0x4b, 0x94, 0xff, 0x14, 0x48, 0x36, 0xbd, 0x1c, 0x09, 0x83, 0xf1, 0x07, 0xd0, 0x29,
	0x7c, 0xb5, 0xe0, 0x16, 0xd4, 0x9f, 0x98, 0xf6, 0x15, 0xaa, 0xe1, 0x2e, 0xb4, 0x0c, 0x4b, 0x33,
	0x74, 0x62, 0xb9, 0x48, 0x1a, 0xcf, 0xa1, 0x5b, 0xdc, 0x60, 0xdc, 0x83, 0xb6, 0x65, 0x4f, 0x4d,
	0xf2, 0x8a, 0x98, 0x0e, 0xaa, 0x61, 0x80, 0xa6, 0x66, 0xda, 0x0e, 0xd1, 0x91, 0xc4, 0x5d, 0x9a,
	0x6d, 0x3d, 0x25, 0x8e, 0x4b, 0x74, 0x24, 0xe3, 0x3e, 0x80, 0x63, 0xda, 0x57, 0x53, 0xe7, 0x82,
	0x10, 0x1d, 0x35, 0xb8, 0xfb, 0x09, 0x25, 0x64, 0x2a, 0xc2, 0xec, 0xe3, 0x0e, 0xec, 0x5f, 0x5a,
	0xcf, 0x2d, 0xfb, 0xca, 0x42, 0x30, 0x1e, 0x42, 0x33, 0xdd, 0x21, 0x2e, 0x78, 0x79, 0xa1, 0xab,
	0x2e, 0x49, 0xc5, 0x75, 0x62, 0x12, 0x97, 0x20, 0x69, 0xfc, 0xbb, 0x04, 0xdd, 0xe2, 0xec, 0xf2,
	0x34, 0x55, 0x2d, 0x4b, 0xb3, 0xc6, 0x83, 0x65, 0xb1, 0x0d, 0xdb, 0x42, 0x12, 0x46, 0xd0, 0xd5,
	0x6c, 0xcb, 0x71, 0xe9, 0xa5, 0x26, 0x90, 0x3d, 0x7c, 0x04, 0x48, 0x37, 0x1c, 0xf5, 0xdc, 0x24,
	0xfa, 0xf4, 0x15, 0x99, 0x18, 0x9a, 0x49, 0x90, 0x8c, 0xdb, 0xd0, 0x20, 0xaf, 0xb8, 0x44, 0x1d,
	0x1f, 0x42, 0xef, 0x85, 0xe1, 0x68, 0xc4, 0x34, 0x55, 0x8b, 0xd8, 0x97, 0x0e, 0x6a, 0x70, 0xe8,
	0xc2, 0x54, 0x2d, 0x8b, 0xe8, 0xd3, 0x94, 0xd5, 0xc4, 0x07, 0xd0, 0xa1, 0xb6, 0xaa, 0x4f, 0x27,
	0xea, 0x97, 0x2a, 0xd5, 0xd1, 0x3e, 0x3e, 0x86, 0x07, 0x8e, 0x36, 0x21, 0xfa, 0x25, 0x17, 0x2e,
	0xc5, 0x6c, 0xf1, 0x3b, 0x5e, 0x11, 0xd5, 0x9d, 0x10, 0x8a, 0xda, 0xfc, 0x36, 0x17, 0xb6, 0x69,
	0x68, 0x04, 0x01, 0x4f, 0x4f, 0xa8, 0xf0, 0xda, 0x5d, 0x52, 0x82, 0x3a, 0x3c, 0xbd, 0x14, 0xb1,
	0x2d, 0x97, 0xaa, 0xa9, 0x40, 0x77, 0xec, 0x6c, 0xde, 0xaf, 0xfb, 0xd5, 0xea, 0xc0, 0xfe, 0xb9,
	0x69, 0x6b, 0xcf, 0x09, 0x4d, 0x9b, 0xa5, 0x51, 0xc3, 0x35, 0x34, 0xd5, 0x44, 0x12, 0xbf, 0xcd,
	0x0b, 0xf5, 0x99, 0x4d, 0xd1, 0x9e, 0xf8, 0x69, 0x58, 0x36, 0x4d, 0x1b, 0xc1, 0xfb, 0x60, 0xbc,
	0xb8, 0x50, 0x35, 0x17, 0xd5, 0xcf, 0x66, 0xf7, 0x5f, 0xc9, 0x0e, 0x8b, 0x6e, 0xfd, 0x19, 0xc3,
	0x2f, 0xa1, 0xff, 0x94, 0x25, 0x19, 0xa8, 0x7b, 0x89, 0x87, 0x4f, 0x2a, 0x1f, 0xf1, 0xec, 0x03,
	0xe7, 0xf8, 0x7f, 0xef, 0xf0, 0xa6, 0x2f, 0xac, 0x52, 0xfb, 0x50, 0x3a, 0x97, 0xff, 0x90, 0xa4,
	0xd7, 0x4d, 0xf1, 0x95, 0xfe, 0xd1, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x77, 0x47, 0xa2, 0x59,
	0xbb, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TrafficServiceClient is the client API for TrafficService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TrafficServiceClient interface {
	GetTrafficData(ctx context.Context, in *TrafficRequest, opts ...grpc.CallOption) (TrafficService_GetTrafficDataClient, error)
}

type trafficServiceClient struct {
	cc *grpc.ClientConn
}

func NewTrafficServiceClient(cc *grpc.ClientConn) TrafficServiceClient {
	return &trafficServiceClient{cc}
}

func (c *trafficServiceClient) GetTrafficData(ctx context.Context, in *TrafficRequest, opts ...grpc.CallOption) (TrafficService_GetTrafficDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TrafficService_serviceDesc.Streams[0], "/trafficproxy.TrafficService/GetTrafficData", opts...)
	if err != nil {
		return nil, err
	}
	x := &trafficServiceGetTrafficDataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TrafficService_GetTrafficDataClient interface {
	Recv() (*TrafficResponse, error)
	grpc.ClientStream
}

type trafficServiceGetTrafficDataClient struct {
	grpc.ClientStream
}

func (x *trafficServiceGetTrafficDataClient) Recv() (*TrafficResponse, error) {
	m := new(TrafficResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TrafficServiceServer is the server API for TrafficService service.
type TrafficServiceServer interface {
	GetTrafficData(*TrafficRequest, TrafficService_GetTrafficDataServer) error
}

// UnimplementedTrafficServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTrafficServiceServer struct {
}

func (*UnimplementedTrafficServiceServer) GetTrafficData(req *TrafficRequest, srv TrafficService_GetTrafficDataServer) error {
	return status.Errorf(codes.Unimplemented, "method GetTrafficData not implemented")
}

func RegisterTrafficServiceServer(s *grpc.Server, srv TrafficServiceServer) {
	s.RegisterService(&_TrafficService_serviceDesc, srv)
}

func _TrafficService_GetTrafficData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TrafficRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TrafficServiceServer).GetTrafficData(m, &trafficServiceGetTrafficDataServer{stream})
}

type TrafficService_GetTrafficDataServer interface {
	Send(*TrafficResponse) error
	grpc.ServerStream
}

type trafficServiceGetTrafficDataServer struct {
	grpc.ServerStream
}

func (x *trafficServiceGetTrafficDataServer) Send(m *TrafficResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _TrafficService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "trafficproxy.TrafficService",
	HandlerType: (*TrafficServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetTrafficData",
			Handler:       _TrafficService_GetTrafficData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "trafficproxy.proto",
}
